all:
  hosts:
     192.168.9.204 ansible_ssh_user=jenkins ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3
     192.168.9.205 ansible_ssh_user=jenkins ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3
  
