- name: Install & configure Laod Balancer
  apt:
    name: haproxy
    state : present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
        
- name: "Copying configuration haproxy "
  template: 
        src: "haproxy.cfg"
        dest: "/etc/haproxy/haproxy.cfg"

- name: Restart service haproxy
  service: 
     name: "haproxy"
     state: restarted
     enabled: yes
  become: yes
