- name: Install & configure Laod Balancer
  apt:
    name: haproxy
    state : present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
     
- name: Copy haproxy.cfg to the managed node
  stat: path=/etc/haproxy/haproxy.cfg
  command: mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.old
  
  template: 
     src: haproxy.cfg
     dest: /etc/haproxy/

- name: Restart service haproxy
  service: 
     name: "haproxy"
     state: restarted
     enabled: yes
  become: yes
