- name: Install & configure Laod Balancer
  apt:
    name: 
       - haproxy
       - firewalld
    state : present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
        
- name: "Copying configuration haproxy "
  template: 
        src: "haproxy.cfg"
        dest: "/etc/haproxy/haproxy.cfg"

- name: permit traffic in default
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled

- name: permit traffic in default
  ansible.posix.firewalld:
    port: 9000/tcp
    permanent: yes
    state: enabled

- name: Restart service firewall
  service:
     name: "firewalld"
     state: started
     enabled: yes
  become: yes

- name: Restart service haproxy
  service: 
     name: "haproxy"
     state: restarted
     enabled: yes
  become: yes
