- name: "Install & configure Laod Balancer"
  apt:
    name: haproxy
    state : present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  
- name: "Check haproxy.cfg"
  stat: path=/etc/haproxy/haproxy.cfg
  register: haproxy.cfg.old

- name: "Move haproxy.cfg to haproxy.old"
  command: mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.old
  when: haproxy.cfg.old.old
     
- name: "Copy haproxy.cfg to the managed node"
  template: 
     src: haproxy.cfg
     dest: /etc/haproxy/

- name: Restart service haproxy
  service: 
     name: "haproxy"
     state: restarted
     enabled: yes
  become: yes
